### ISSUE TITLE
Avoid using RM

### ISSUE THREAD

**Issue by josephfusco** [josephfusco/wp-self-destruct#1]
We should avoid using `rm` to delete the install. It is not the safest thing to be doing. I personally use https://www.npmjs.com/package/trash now to remove files locally but am not sure how that would work for a server. Maybe an option to delete with either rm or trash (if installed globally)?

**Comment by fiott248** [comment]
well Using Trash will not fully Delete the files it will just move them to trash if that`s what your looking for. if you want to fully delete the files with trash you will need to use also trash-empty here is a repo https://github.com/sindresorhus/empty-trash

**Comment by fiott248** [comment]
How about we use unlink function to delete all the files globally ?

**Comment by Ayesh** [comment]
A recursive function that deletes the given file and scans deeper should do the trick. On the same note, should we keep the `mysqladmin` call too? It will be unavailable for most Windows environments too, and carries about the same command injection vulnerabilities. 

We'll never know, but if the mysql user has permission to drop databases, I think we should use it and just run standard SQL to nuke the database.

**Comment by isaactorresmichel** [comment]
Added a PR to replace rm -r using PHP's recursive iterators, unlink and rmdir. All the code is formatted using WordPress coding standards. Hope it helps.

**Comment by josephfusco** [comment]
Thank you @fiott248 @Ayesh @isaactorresmichel !

I decided to merge https://github.com/josephfusco/wp-self-destruct/pull/3/commits/8f3a7b8abcfc13b871ff0785bde0e1130d4b257b
