### ISSUE TITLE
What's wrong with the native CLI approach?

### ISSUE THREAD

**Issue by ianwijma** [josephfusco/wp-self-destruct#5]
LOVE the idea, but what's the advantage over using native WP CLI?

```bash
wp db reset && rm -r ./*
```
or
```bash
wp db reset --yes && rm -r ./*
```

**Comment by josephfusco** [comment]
Hey @ianwijma,

Thanks for the feedback! The command `wp db reset` only resets the database whereas this plugin deletes the database. In regards to deleting the site's files, this plugin uses `ABSPATH` to delete, so you could run the command from anywhere in the WordPress site where the commands you provided would have to be ran from the root of the site.
